import type { Metadata } from "next";
import { ReactNode } from "react";
import { Inter, Roboto_Mono } from "next/font/google";
import { NextIntlClientProvider, useMessages } from "next-intl";
import { headers } from "next/headers";
import { notFound } from "next/navigation";
import "@/styles/globals.css";
import "@/styles/nprogress.css";
import "grapesjs/dist/css/grapes.min.css";
import ReactQueryProvider from "./providers/ReactQueryProvider";
import ToastProvider from "@/components/toast/ToastProvider";

// Font cấu hình
const inter = Inter({
  variable: "--font-sans",
  subsets: ["latin"],
});
const mono = Roboto_Mono({
  variable: "--font-mono",
  subsets: ["latin"],
});
// Metadata cho trang
export const metadata: Metadata = {
  title: "Flatform - Demo",
  description: "Generated by KukuIT",
};

// Layout đa ngôn ngữ
export default function LocaleLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const messages = useMessages();
  const headersList = headers();
  const locale = headersList.get("x-locale") || "vi";

  return (
    <html lang={locale} suppressHydrationWarning>
      <body
        className={`${inter.variable} ${mono.variable} antialiased`}
        suppressHydrationWarning
      >
        <NextIntlClientProvider locale={locale} messages={messages}>
          <ReactQueryProvider>
            <ToastProvider />
            {children}
          </ReactQueryProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
